[package]
name = "tcl_main_sc-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.tcl_main_sc]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.47.4"
default-features = false
